stages:
  - test
  - build

test:
    stage: test
    image: node:21.5-alpine3.19
    before_script:
        - npm install
    script:
        - npx vitest --reporter=junit --outputFile=./junit-report.xml
    artifacts:
      when: always
      paths:
        - junit-report.xml
      reports:
        junit: junit-report.xml
    tags:
        - docker
    rules:
        - if: $CI_COMMIT_BRANCH == "production"

build:
  stage: build
  image: node:21.5-alpine3.19
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
